data <- list(
  `conversationId` = "",
  `dados.buscaInteiroTeor` = "locação temporada",
  `dados.pesquisarComSinonimos` = "S",
  `dados.pesquisarComSinonimos` = "S",
  `dados.buscaEmenta` = "",
  `dados.nuProcOrigem` = "",
  `dados.nuRegistro` = "",
  `agenteSelectedEntitiesList` = "",
  `contadoragente` = "0",
  `contadorMaioragente` = "0",
  `codigoCr` = "",
  `codigoTr` = "",
  `nmAgente` = "",
  `juizProlatorSelectedEntitiesList` = "",
  `contadorjuizProlator` = "0",
  `contadorMaiorjuizProlator` = "0",
  `codigoJuizCr` = "",
  `codigoJuizTr` = "",
  `nmJuiz` = "",
  `classesTreeSelection.values` = "",
  `classesTreeSelection.text` = "",
  `assuntosTreeSelection.values` = "",
  `assuntosTreeSelection.text` = "",
  `secoesTreeSelection.values` = "",
  `secoesTreeSelection.text` = "",
  `dados.dtJulgamentoInicio` = "",
  `dados.dtJulgamentoFim` = "",
  `dados.dtPublicacaoInicio` = "",
  `dados.dtPublicacaoFim` = "",
  `dados.origensSelecionadas` = "T",
  `dados.origensSelecionadas` = "R",
  `tipoDecisaoSelecionados` = "A",
  `tipoDecisaoSelecionados` = "D",
  `dados.ordenarPor` = "dtPublicacao"
)

r <- httr::POST(url = "https://esaj.tjac.jus.br/cjsg/resultadoCompleta.do", body = data, encode = "form", httr::write_disk("data-raw/busca.html", overwrite = TRUE))